version: "3"

services:
  keycloak:
    image: "jboss/keycloak:16.1.1"
    depends_on:
      - "postgres"
    environment:
      - "DB_VENDOR=postgres"
      - "KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}"
      - "KEYCLOAK_USER=${KEYCLOAK_USERNAME}"
      - "DB_DATABASE=${POSTGRES_DBNAME}"
      - "DB_PASSWORD=${POSTGRES_PASSWORD}"
      - "DB_ADDR=postgres"
      - "DB_USER=${POSTGRES_USERNAME}"
    networks:
      - "keycloak-user-fts"
    ports:
      - "8080:8080"

  postgres:
    image: "postgres:14-alpine"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USERNAME}"
      - "POSTGRES_DB=${POSTGRES_DBNAME}"
    networks:
      - "keycloak-user-fts"
    ports:
      - "5432:5432"

networks:
  keycloak-user-fts:
    driver: "bridge"
